### ISSUE TITLE
No handlers could be found for logger "bag_player"

### ISSUE THREAD

**Issue by ribinmathew** [masasin/pyrosbag#4]
Traceback (most recent call last):
  File "/home/ribin/PycharmProjects/PointCloud/ros_pcl_integration.py", line 12, in <module>
    files.play()
  File "/home/ribin/.local/lib/python2.7/site-packages/pyrosbag/pyrosbag.py", line 234, in play
    arguments.extend(self.filenames)
TypeError: 'Bag' object is not iterable

getting this error while trying to play a bag file

**Comment by callumtyler** [comment]
I have also had this issue - see below: 

No handlers could be found for logger "bag_player"
Traceback (most recent call last):
  File "pyrosbag_test.py", line 7, in <module>
    example.play()
  File "/usr/local/lib/python2.7/site-packages/pyrosbag/pyrosbag.py", line 262, in play
    stdin=stdin, stdout=stdout, stderr=stderr)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
